# Generated by Django 2.1.7 on 2019-05-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='urltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.URLType'),
        ),
        migrations.AlterField(
            model_name='urltype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
